# Generated by Django 4.2.7 on 2023-11-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField()),
                ('loan_date', models.TextField()),
                ('loan_total', models.FloatField()),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrestamosPermitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(blank=True, null=True)),
                ('loan_type', models.TextField(blank=True, null=True)),
                ('loan_date', models.TextField(blank=True, null=True)),
                ('loan_total', models.FloatField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestamos_permitidos',
                'managed': False,
            },
        ),
    ]
