# Generated by Django 4.2.7 on 2023-11-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_transferencia_delete_movimientos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={},
        ),
    ]
