# Generated by Django 4.2.7 on 2023-11-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_alter_transferencia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={'managed': False},
        ),
    ]
