# Generated by Django 4.2.7 on 2023-11-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_prestamospermitidos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamospermitidos',
            table='prestamos_permitidos',
        ),
    ]
