# Generated by Django 4.2.7 on 2023-11-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_delete_auditoriacuenta_delete_cardbrand_delete_cards_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='PrestamosPermitidos',
        ),
    ]
