# Generated by Django 4.2.7 on 2023-12-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_delete_prestamo_delete_prestamospermitidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
    ]
